'use client';

import { useState, useEffect } from 'react';
import { Download, Mail } from 'lucide-react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { toast } from 'sonner';
import { AuditResult } from '@/types/audit';

interface PDFExportProps {
  auditResult: AuditResult;
}

export default function PDFExport({ auditResult }: PDFExportProps) {
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [email, setEmail] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [hasEmail, setHasEmail] = useState(false);

  useEffect(() => {
    // Check if email is already stored
    const storedEmail = localStorage.getItem('aioverdose_user_email');
    if (storedEmail) {
      setHasEmail(true);
      setEmail(storedEmail);
    }
  }, []);

  const validateEmail = (email: string) => {
    const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return regex.test(email);
  };

  const generatePDF = async (userEmail: string) => {
    try {
      setIsLoading(true);

      // Create PDF
      const pdf = new jsPDF();
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      let yPos = 20;

      // Header
      pdf.setFontSize(24);
      pdf.setFont('helvetica', 'bold');
      pdf.text('AI Search Readiness Report', pageWidth / 2, yPos, {
        align: 'center',
      });

      yPos += 15;
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(100);
      pdf.text('aioverdose.com', pageWidth / 2, yPos, { align: 'center' });

      // Report metadata
      yPos += 12;
      pdf.setTextColor(0);
      pdf.setFontSize(11);
      pdf.text(`URL: ${auditResult.url || 'N/A'}`, 20, yPos);

      yPos += 8;
      pdf.text(`Date: ${new Date().toLocaleDateString()}`, 20, yPos);

      yPos += 8;
      pdf.text(
        `Overall Score: ${auditResult.overallScore}/100 (Grade: ${auditResult.grade})`,
        20,
        yPos
      );

      // Score breakdown table
      yPos += 15;
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Score Breakdown', 20, yPos);

      yPos += 10;
      const categoryData = Object.entries(auditResult.categories).map(
        ([name, data]) => [
          name.charAt(0).toUpperCase() + name.slice(1),
          `${data.score}/100`,
          data.score >= 70 ? 'Pass' : data.score >= 50 ? 'Warning' : 'Fail',
        ]
      );

      autoTable(pdf, {
        startY: yPos,
        head: [['Category', 'Score', 'Status']],
        body: categoryData,
        theme: 'grid',
        headStyles: {
          fillColor: [59, 130, 246],
          textColor: 255,
          fontStyle: 'bold',
        },
        bodyStyles: {
          textColor: 0,
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245],
        },
      });

      yPos = (pdf as any).lastAutoTable.finalY + 15;

      // Top action items
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Top 5 Action Items', 20, yPos);

      yPos += 10;
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');

      const topActions = auditResult.actionPlan.slice(0, 5);
      topActions.forEach((action, index) => {
        const priority =
          action.impact === 'high'
            ? '🔴 HIGH'
            : action.impact === 'medium'
              ? '🟡 MEDIUM'
              : '🟢 LOW';

        const text = `${index + 1}. ${action.title} (${priority})`;
        const wrappedText = pdf.splitTextToSize(text, pageWidth - 40);

        wrappedText.forEach((line: string) => {
          pdf.text(line, 20, yPos);
          yPos += 6;
        });

        yPos += 4;
      });

      // Footer
      yPos = pageHeight - 20;
      pdf.setFontSize(9);
      pdf.setTextColor(150);
      pdf.text(
        'Generated by aioverdose.com | AI Search Strategy for the Citation Era',
        pageWidth / 2,
        yPos,
        { align: 'center' }
      );

      // Save PDF
      pdf.save(
        `AI-Search-Readiness-Report-${new Date().toISOString().split('T')[0]}.pdf`
      );

      // Store email
      localStorage.setItem('aioverdose_user_email', userEmail);

      // Subscribe to newsletter (placeholder)
      try {
        await fetch('https://formspree.io/f/YOUR_FORM_ID', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            email: userEmail,
            _subject: 'Newsletter Signup - PDF Download',
          }),
        }).catch(() => {
          // Silently fail - still download PDF
        });
      } catch (err) {
        // Ignore newsletter subscription errors
      }

      setShowEmailModal(false);
      toast.success('Report downloaded! Check your inbox for AI Search Watch.');
    } catch (error) {
      console.error('PDF generation error:', error);
      toast.error('Failed to generate PDF. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = async () => {
    if (hasEmail) {
      await generatePDF(email);
    } else {
      setShowEmailModal(true);
    }
  };

  const handleEmailSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateEmail(email)) {
      toast.error('Please enter a valid email address');
      return;
    }

    await generatePDF(email);
  };

  return (
    <>
      {/* Download Button */}
      <button
        onClick={handleDownload}
        disabled={isLoading}
        className="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white font-medium rounded-lg transition-colors"
      >
        <Download size={18} />
        {isLoading ? 'Generating...' : 'Download PDF Report'}
      </button>

      {/* Email Gate Modal */}
      {showEmailModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-900 rounded-lg max-w-md w-full p-8 space-y-6">
            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                Download Your Report
              </h2>
              <p className="text-gray-600 dark:text-gray-400">
                Enter your email to download the PDF and subscribe to AI Search
                Watch (our weekly newsletter).
              </p>
            </div>

            <form onSubmit={handleEmailSubmit} className="space-y-4">
              <div>
                <label
                  htmlFor="email"
                  className="block text-sm font-medium text-gray-900 dark:text-white mb-2"
                >
                  Email Address
                </label>
                <input
                  type="email"
                  id="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="your@email.com"
                  className="w-full px-4 py-2 bg-gray-100 dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-lg text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div className="flex gap-3">
                <button
                  type="button"
                  onClick={() => setShowEmailModal(false)}
                  className="flex-1 px-4 py-2 bg-gray-200 dark:bg-gray-800 hover:bg-gray-300 dark:hover:bg-gray-700 text-gray-900 dark:text-white font-medium rounded-lg transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isLoading}
                  className="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white font-medium rounded-lg transition-colors flex items-center justify-center gap-2"
                >
                  <Mail size={16} />
                  {isLoading ? 'Generating...' : 'Download'}
                </button>
              </div>
            </form>

            <p className="text-xs text-gray-500 dark:text-gray-500">
              We'll send you the report + weekly AI search updates. Unsubscribe
              anytime.
            </p>
          </div>
        </div>
      )}
    </>
  );
}
