import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | aioverdose',
  description: 'Legal terms governing your use of aioverdose.com.',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      <article className="max-w-3xl mx-auto px-4 py-16 prose prose-invert">
        <div className="mb-6 pb-6 border-b border-gray-300 dark:border-gray-700">
          <p className="text-sm text-gray-600 dark:text-gray-400 m-0">
            Last Updated: January 2026
          </p>
        </div>

        <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">Terms of Service</h1>

        <p className="text-lg text-gray-700 dark:text-gray-300">
          By accessing <strong>aioverdose.com</strong>, you agree to these terms. If you disagree, please don't use the site.
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By visiting and using aioverdose.com (the "Service"), you accept and agree to be bound by these Terms of Service. We may update these terms at any time. Continued use after changes means you accept the new terms.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          aioverdose.com provides:
        </p>
        <ul>
          <li>Educational content about AI search systems and search engine optimization</li>
          <li>Free tools (AI Search Readiness Audit, etc.) to analyze web content</li>
          <li>Guides, research, and best practices for GEO (Generative Engine Optimization)</li>
          <li>A newsletter with weekly AI search intelligence</li>
        </ul>
        <p>
          All content and tools are provided on an "as-is" basis.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          Most of our site doesn't require an account. If you create an account (for future membership features), you're responsible for:
        </p>
        <ul>
          <li>Keeping your login credentials confidential</li>
          <li>Notifying us immediately of unauthorized access</li>
          <li>All activities under your account</li>
        </ul>

        <h2>4. Acceptable Use</h2>
        <p>
          You agree <strong>not</strong> to:
        </p>
        <ul>
          <li>Scrape, automate, or bulk-submit content to our tools</li>
          <li>Attempt to reverse-engineer or access our code</li>
          <li>Use the site for illegal purposes or to harm others</li>
          <li>Spam or abuse our contact forms or newsletter</li>
          <li>Launch attacks, viruses, or malware</li>
          <li>Violate anyone's intellectual property or privacy rights</li>
          <li>Misrepresent yourself or use fake information</li>
        </ul>
        <p>
          Violations may result in account termination and legal action.
        </p>

        <h2>5. Intellectual Property Rights</h2>

        <h3>Our Content</h3>
        <p>
          All articles, guides, designs, and original content on aioverdose.com are owned by us and protected by copyright. You may read and share for personal, non-commercial use, but may not republish without permission.
        </p>

        <h3>Your Submissions</h3>
        <p>
          If you submit feedback, suggestions, or content, you grant us a non-exclusive, royalty-free license to use it (unless you mark it as confidential).
        </p>

        <h3>Tool Output</h3>
        <p>
          Audit results and recommendations generated by our tools are yours to use as you see fit. We do not claim ownership of your website data or analysis output.
        </p>

        <h2>6. Disclaimer of Warranties</h2>
        <p>
          <strong>Important:</strong> Our tools and content are educational and informational only. We make <strong>no warranties</strong>, express or implied, about:
        </p>
        <ul>
          <li><strong>Guaranteed results:</strong> The AI Search Readiness Audit scores don't guarantee your site will rank in AI search results. AI algorithms change constantly and are controlled by third parties.</li>
          <li><strong>Professional advice:</strong> Nothing here is legal, financial, or SEO advice. Consult professionals for specific guidance.</li>
          <li><strong>Accuracy:</strong> While we aim for accuracy, AI search is rapidly evolving. Information may become outdated.</li>
          <li><strong>Uninterrupted service:</strong> We may take the site offline for maintenance or other reasons.</li>
          <li><strong>Third-party content:</strong> We're not responsible for external links or third-party services.</li>
        </ul>

        <h2>7. Limitation of Liability</h2>
        <p>
          <strong>To the fullest extent allowed by law:</strong> We are not liable for any indirect, incidental, special, or consequential damages, including lost profits or data, even if we've been told of the possibility.
        </p>
        <p>
          Our total liability is limited to $0 (if you can't recover anything from us, that's your only remedy).
        </p>

        <h2>8. Indemnification</h2>
        <p>
          You agree to defend and indemnify us from any claims, damages, or legal fees arising from:
        </p>
        <ul>
          <li>Your use of the Service</li>
          <li>Violation of these terms</li>
          <li>Infringement of others' rights</li>
        </ul>

        <h2>9. Third-Party Links</h2>
        <p>
          We may link to external sites (tools, resources, articles). We're not responsible for their content, accuracy, or practices. Use at your own risk and review their privacy policies.
        </p>

        <h2>10. Affiliate Links & Disclosure</h2>
        <p>
          Some links on our site are affiliate links. We earn a commission if you purchase through them. These are clearly marked or disclosed. This doesn't affect your purchase price.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These terms are governed by the laws of the State of Delaware, USA, without regard to conflict of law principles. You agree to submit to the exclusive jurisdiction of Delaware courts.
        </p>

        <h2>12. Severability</h2>
        <p>
          If any provision is found invalid or unenforceable, the remaining terms continue in effect.
        </p>

        <h2>13. Entire Agreement</h2>
        <p>
          These terms (along with our Privacy Policy and Cookie Policy) constitute the entire agreement between you and aioverdose.com regarding your use of the Service.
        </p>

        <h2>14. Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. Material changes will be announced via email or a prominent site banner. Continued use after notification constitutes acceptance.
        </p>

        <h2>15. Contact</h2>
        <p>
          Questions or concerns about these terms?
        </p>
        <ul>
          <li>Email: <strong>hello@aioverdose.com</strong></li>
          <li><a href="/contact">Contact Form</a></li>
        </ul>

        <hr className="my-12 border-gray-300 dark:border-gray-700" />
        <p className="text-sm text-gray-600 dark:text-gray-400">
          © 2026 aioverdose.com. All rights reserved.
        </p>
      </article>
    </div>
  );
}
